# -*- coding: utf-8 -*-
"""a.single neuron.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_MKgJwitWDfpvSzAzZwheMEEUpo5Jtu0
"""

#Sayyidina Auliya
#21091397034

#inisialisasi library
import numpy as np

#input layer feature 10
inputs = [1.2,5.1,2.1,3.7,4,2,9.1,6,2.7,8.1]
weights = [3.1,2.1,8.7,4.2,8,4,3.3,7,1.9,4.6]

#neuron 1
bias = 3

#menampilkan keluaran
outputs = np.dot(weights, inputs) + bias
print(outputs)