# -*- coding: utf-8 -*-
"""b.multi neuron.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BdsbT-SzS9REktDgWSp6EhNtlRfOmaPp
"""

#Sayyidina Auliya
#21091397034

#inisialisasi library
import numpy as np

#input layer feature 10
inputs = [1,2,3,2.5,8,1.4,3,2.1,1.12,4.1]
weights = [
    [0.2,0.8,-0.5,1.0,0.3,1.2,0.32,-0.18,0.30,0.6],
    [0.5,-0.91,0.26,-0.5,1.0,0.7,0.6,0.47,-0.21,0.3],
    [-0.26,-0.27,0.17,0.87,0.99,1.14,0.71,-0.03,0.29,-1.0],
    [0.17,-0.3,-0.4,0.6,1.03,0.45,0.7,0.55,-1.0,1.0],
    [0.1,0.9,-0.11,0.6,0.87,2.0,-0.26,0.10,-0.28,0.28]
]

#neuron 5
biases = [2,3,0.5,1,0.8]

#menampilkan keluaran
outputs = np.dot (weights, inputs) + biases
print(outputs)